### ISSUE TITLE
todo: Improve file copy

### ISSUE THREAD

**Issue by Herbivore-sama** [Herbivore-sama/crap_playlist_thing#1]
- [x] add progress bar of some sort
- [x] don't lock up the whole gui while copy is running
- [x] preserve folders
- [x] implement delta copy with hash check 
  - [x] compute initial hash
  - [x] check destination for existing file
  - [x] if found, check hash and overwrite if different 
  - [x] compute hash after copy, and re-copy if different from initial hash

**Comment by Herbivore-sama** [comment]
not exactly a progress bar, more a file completed message, but it'll do
