### ISSUE TITLE
todo: Process multiple playlists in one run

### ISSUE THREAD

**Issue by Herbivore-sama** [Herbivore-sama/crap_playlist_thing#2]
- [ ] allow user to select more than one file, each selection adds to list
- [ ] add "clear playlists" button to remove all selected playlists
- [ ] handle storing all of them to last run file
- [ ] iterate over each
- [x] report progress somehow

**Comment by Herbivore-sama** [comment]
progress reporting already inherent as of last version, I don't think iterating will cause a problem with how I plan to make it work
need to rework writing/reading to/from json and fileInfo object to accept a tuple rather than a string
might just convert tuple to list instead actually
