### ISSUE TITLE
todo: Add CLI options

### ISSUE THREAD

**Issue by Herbivore-sama** [Herbivore-sama/crap_playlist_thing#3]
- [ ] specify all settings
- [ ] choose copy or convert
- [ ] execute on given info
